---
# External DNS - Automatically manages DNS records in Cloudflare
# Creates/updates A records for LoadBalancer services and Ingresses
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.14.5"
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    provider: cloudflare

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token

    # Domain filter - only manage records for your domain
    domainFilters:
      - ${CLUSTER_DOMAIN:=example.com}

    # Policy: sync will create and delete records
    # upsert-only will only create/update, never delete
    policy: sync

    # Sources to watch for DNS records
    sources:
      - service
      - ingress

    # Cloudflare-specific settings
    extraArgs:
      - --cloudflare-proxied=false  # Set to true to enable CF proxy
      - --cloudflare-dns-records-per-page=500

    # TXT record ownership
    txtOwnerId: ${CLUSTER_NAME:=oci-prod}
    txtPrefix: "externaldns-"

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

    serviceMonitor:
      enabled: false  # Enable if Prometheus Operator is installed
---
# Secret for Cloudflare API Token (to be created via SOPS or manually)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-token
#   namespace: external-dns
# type: Opaque
# stringData:
#   api-token: "your-cloudflare-api-token"
