---
# HashiCorp Vault for secrets management
# Stores certificates, API keys, and sensitive configuration
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "0.28.1"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  values:
    global:
      enabled: true
      namespace: vault

    server:
      enabled: true
      image:
        repository: "hashicorp/vault"
        tag: "1.17.6"

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: vault.${CLUSTER_DOMAIN:=example.com}
            paths:
              - /
        tls:
          - secretName: vault-tls
            hosts:
              - vault.${CLUSTER_DOMAIN:=example.com}

      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: ${STORAGE_CLASS:=oci-bv}

      standalone:
        enabled: true
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "file" {
            path = "/vault/data"
          }

      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m

    ui:
      enabled: true
      serviceType: "ClusterIP"

    injector:
      enabled: true
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 128Mi
          cpu: 100m
